### ISSUE TITLE
Config to prevent upgrading diamond dowsing rod

### ISSUE THREAD

**Issue by Dominance** [rosche/ore-dowsing#1]
Just want to prevent it from being to powerful in my pack. If this is possible that would be awesome!

**Comment by rosche** [comment]
You  bet, good idea.

**Comment by Dominance** [comment]
You know what else would be great is if I could choose what item is needed to upgrade it. Have the config set to default " item needed to upgrade = minecraft:diamond " and the user could switch that. Would work just as well as toggling the feature on / off. I like the feature just want it to cost a little more.

**Comment by rosche** [comment]
I've added the config file in version 0.7.  It can be used to control almost everything about the mod, including the above.  1.7.10 version is uploaded, 1.8 is in the works.

**Comment by rosche** [comment]
I've uploaded the 1.8 version which includes the config file.
