### ISSUE TITLE
Crash with Diamond rod on Beyond Reality Divergence 1.2.4

### ISSUE THREAD

**Issue by Towsty** [rosche/ore-dowsing#2]
Crashed when using the diamond rod:

http://pastebin.com/06aAjB05

**Comment by Dominance** [comment]
Yeah another report http://pastebin.com/VL4HiDmQ This is one without BNB gaming just to rule it out.

**Comment by Squall0182** [comment]
http://pastebin.com/ECqiAmvM same here, tried with any dowsing machine, works fine until it detects a block, heres the other two reports aswell:
http://pastebin.com/JvW8B8Sd
http://pastebin.com/kiATeUbh

**Comment by rosche** [comment]
Sorry, I'll have a fix for this soon.  Issue is stand-alone server doesn't have access to LWJGL.

**Comment by Dominance** [comment]
Thanks Rosche!

**Comment by rosche** [comment]
This issue is fixed in release 0.6, please check it out.

**Comment by Towsty** [comment]
Works great now, thanks Rosche!
